# Generated by Django 4.1.4 on 2023-02-04 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lname', models.CharField(blank=True, max_length=60, null=True)),
                ('fathername', models.CharField(blank=True, max_length=60, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('family', models.ManyToManyField(blank=True, null=True, related_name='myfamily', to='card.card_main')),
                ('friends', models.ManyToManyField(blank=True, related_name='myfriend', to='card.card_main')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_main', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChooseCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=35, null=True)),
                ('position', models.CharField(blank=True, max_length=60, null=True)),
                ('company_address', models.CharField(blank=True, max_length=55, null=True)),
                ('card_works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Tiktok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=65)),
                ('card_tiktoks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('card_photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=15)),
                ('card_phones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=65)),
                ('card_instagrams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=45)),
                ('card_homes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=65)),
                ('card_facebooks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('card_comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='card.card_main')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModels', models.CharField(max_length=35)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='card.choosecars')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(blank=True, max_length=9, null=True)),
                ('car_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car', to='card.color')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car', to='card.car_model')),
                ('card_cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='card.card_main')),
                ('choose_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='card.choosecars')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BooleanField(blank=True, null=True)),
                ('lname', models.BooleanField(blank=True, null=True)),
                ('father_name', models.BooleanField(blank=True, null=True)),
                ('birth_year', models.BooleanField(blank=True, null=True)),
                ('features', models.BooleanField(blank=True, null=True)),
                ('family', models.BooleanField(blank=True, null=True)),
                ('friends', models.BooleanField(blank=True, null=True)),
                ('facebook', models.BooleanField(blank=True, null=True)),
                ('tiktok', models.BooleanField(blank=True, null=True)),
                ('instagram', models.BooleanField(blank=True, null=True)),
                ('images', models.BooleanField(blank=True, null=True)),
                ('phone', models.BooleanField(blank=True, null=True)),
                ('home', models.BooleanField(blank=True, null=True)),
                ('work', models.BooleanField(blank=True, null=True)),
                ('car', models.BooleanField(blank=True, null=True)),
                ('card_about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_main1', to='card.card_main')),
            ],
        ),
    ]
