# Generated by Django 4.1.4 on 2023-01-12 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(blank=True, max_length=35, null=True)),
                ('car_number', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lname', models.CharField(blank=True, max_length=60, null=True)),
                ('fathername', models.CharField(blank=True, max_length=60, null=True)),
                ('brith_year', models.IntegerField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_main', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(blank=True, max_length=36, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='car_model', serialize=False, to='card.car')),
                ('carModels', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=35, null=True)),
                ('position', models.CharField(blank=True, max_length=60, null=True)),
                ('company_address_city', models.CharField(blank=True, max_length=55, null=True)),
                ('company_address_street', models.CharField(blank=True, max_length=55, null=True)),
                ('card_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Tiktok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=65, null=True)),
                ('card_tiktok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(blank=True, max_length=15, null=True)),
                ('ph_numbers_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=65, null=True)),
                ('card_instagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address_city', models.CharField(blank=True, max_length=45, null=True)),
                ('home_address_street', models.CharField(blank=True, max_length=45, null=True)),
                ('home_number', models.CharField(blank=True, max_length=30, null=True)),
                ('card_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=65, null=True)),
                ('card_facebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook', to='card.card_main')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('card_comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='card.card_main')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car', to='card.color'),
        ),
        migrations.AddField(
            model_name='car',
            name='card_cars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='card.card_main'),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BooleanField()),
                ('lanme', models.BooleanField()),
                ('father_name', models.BooleanField()),
                ('birth_year', models.BooleanField()),
                ('features', models.BooleanField()),
                ('family', models.BooleanField()),
                ('friends', models.BooleanField()),
                ('facebook', models.BooleanField()),
                ('tiktok', models.BooleanField()),
                ('instagram', models.BooleanField()),
                ('images', models.BooleanField()),
                ('phone', models.BooleanField()),
                ('home', models.BooleanField()),
                ('work', models.BooleanField()),
                ('car', models.BooleanField()),
                ('card_about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_main1', to='card.card_main')),
            ],
        ),
    ]
