# Generated by Django 4.1.4 on 2023-01-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car_Model',
        ),
    ]
