# Generated by Django 4.1.4 on 2023-01-12 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='account',
            field=models.CharField(default=datetime.datetime(2023, 1, 12, 20, 29, 39, 558047, tzinfo=datetime.timezone.utc), max_length=65),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagram',
            name='account',
            field=models.CharField(default=datetime.datetime(2023, 1, 12, 20, 29, 51, 782077, tzinfo=datetime.timezone.utc), max_length=65),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiktok',
            name='account',
            field=models.CharField(default=datetime.datetime(2023, 1, 12, 20, 30, 1, 853830, tzinfo=datetime.timezone.utc), max_length=65),
            preserve_default=False,
        ),
    ]
