# Generated by Django 4.1.4 on 2023-01-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_color',
        ),
    ]
