# Generated by Django 4.1.4 on 2023-01-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_main',
            old_name='brith_year',
            new_name='birth_year',
        ),
    ]
