# Generated by Django 4.1.4 on 2023-01-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_model',
            old_name='car_model',
            new_name='car',
        ),
    ]
