# Generated by Django 4.1.4 on 2023-01-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='birth_year',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='car',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='facebook',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='family',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='father_name',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='features',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='friends',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='home',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='images',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='instagram',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='lanme',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='tiktok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='work',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
