# Generated by Django 4.1.4 on 2023-01-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_main',
            name='family',
            field=models.ManyToManyField(blank=True, null=True, related_name='myfamily', to='card.card_main'),
        ),
    ]
