# Generated by Django 4.1.4 on 2022-12-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_main',
            name='family',
        ),
    ]
