# Generated by Django 4.1.4 on 2023-01-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_facebook_account_alter_instagram_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='account',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='account',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='tiktok',
            name='account',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
