# Generated by Django 4.1.4 on 2023-01-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_rename_brith_year_card_main_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='account',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagram',
            name='account',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='tiktok',
            name='account',
            field=models.CharField(max_length=65),
        ),
    ]
