# Generated by Django 4.1.4 on 2023-01-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_car_car_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car_Model',
        ),
    ]
