# Generated by Django 4.1.4 on 2023-01-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_delete_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosecars',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
