# Generated by Django 4.1.4 on 2023-01-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_rename_car_model_car_model_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='car_model',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='car_model', serialize=False, to='card.car'),
        ),
    ]
