# Generated by Django 4.1.4 on 2023-02-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_about_birth_year_alter_about_car_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='lanme',
            new_name='lname',
        ),
    ]
