# Generated by Django 4.1.4 on 2023-01-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_remove_car_model_id_alter_car_model_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_main',
            name='family',
        ),
        migrations.RemoveField(
            model_name='card_main',
            name='friends',
        ),
    ]
