# Generated by Django 4.1.4 on 2023-01-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_card_main_family_card_main_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='card_main',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
