# Generated by Django 4.1.4 on 2023-01-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car', to='card.car_model'),
        ),
    ]
