# Generated by Django 4.1.4 on 2023-01-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_remove_card_main_family_remove_card_main_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_main',
            name='family',
            field=models.ManyToManyField(blank=True, null=True, to='card.card_main'),
        ),
        migrations.AddField(
            model_name='card_main',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='card.card_main'),
        ),
    ]
