# Generated by Django 4.1.4 on 2023-01-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_alter_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='card_comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='comments', serialize=False, to='card.card_main'),
        ),
    ]
