# Generated by Django 4.1.4 on 2023-01-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_car_car_name_alter_car_car_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_main',
            name='family',
            field=models.ManyToManyField(to='card.card_main'),
        ),
        migrations.AlterField(
            model_name='card_main',
            name='friends',
            field=models.ManyToManyField(null=True, to='card.card_main'),
        ),
    ]
