# Generated by Django 4.1.4 on 2023-01-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_alter_card_main_family_alter_card_main_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_main',
            name='family',
            field=models.ManyToManyField(blank=True, null=True, to='card.card_main'),
        ),
        migrations.AlterField(
            model_name='card_main',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='card.card_main'),
        ),
    ]
