# Generated by Django 4.1.4 on 2023-01-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_alter_card_main_family_alter_card_main_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='home_address',
            new_name='home_address_city',
        ),
        migrations.RemoveField(
            model_name='work',
            name='company_address',
        ),
        migrations.AddField(
            model_name='home',
            name='home_address_street',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='home_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='company_address_city',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='company_address_street',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='facebook',
            name='account',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='account',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='tiktok',
            name='account',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
